ecosystem/platform/server/config/routes.rb
# frozen_string_literal: true

# Copyright (c) Aptos
# SPDX-License-Identifier: Apache-2.0

Rails.application.routes.draw do
  devise_for :users, {
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
  }
  ActiveAdmin.routes(self)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    # get ':provider/callback', to: 'sessions#create'
    get 'users/me', to: 'users#me'
    resources :users, only: %i[show update]
  end

  namespace :user do
    root to: redirect('/it1') # creates user_root_path, where users go after confirming email
  end

  # KYC routes
  get 'onboarding/kyc_redirect', to: 'onboarding#kyc_redirect'
  get 'onboarding/kyc_callback', to: 'onboarding#kyc_callback'

  get 'onboarding/email', to: 'onboarding#email'
  post 'onboarding/email', to: 'onboarding#email_update'

  get 'health', to: 'health#health'

  resources :overview, only: %i[index]
  resources :it1_profiles, except: %i[index destroy]

  get 'it1', to: 'welcome#it1'
  root 'welcome#index'
end

ecosystem/platform/server/app/controllers/overview_controller.rb
# frozen_string_literal: true

# Copyright (c) Aptos
# SPDX-License-Identifier: Apache-2.0

class OverviewController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_confirmed!

  def index
    redirect_to root_path
  end
end

ecosystem/platform/server/app/helpers/overview_helper.rb
# Copyright (c) Aptos
# SPDX-License-Identifier: Apache-2.0
# frozen_string_literal: true

module OverviewHelper
end

ecosystem/platform/server/app/views/overview/index.html.erb
<div class="p-6">
   <div class="flex flex-col gap-4">
     <%= render "layouts/flash" %>

    <% if current_user.confirmed_at.nil? %>
      <p class="bg-gray-100 border border-gray-400 text-gray-700 px-4 py-3 rounded">
      Your email has not yet been verified. Didn't receive a verification email? <%= link_to "Re-send verification email", onboarding_email_path, class: "underline" %>
      </p>
    <% end %>

    <p class="bg-gray-100 border border-gray-400 text-gray-700 px-4 py-3 rounded">
      <% if current_user.it1_profile %>
        IT1 application received.
        <%= link_to "Edit your application", edit_it1_profile_path(current_user.it1_profile), class: "underline" %>
      <% else %>
        Registration for IT1 is open!
        <%= link_to "Apply now", it1_path, class: "underline" %>
      <% end %>
    </p>
  </div>
</div>